name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Raku/setup-raku@v1
      - uses: ankane/setup-postgres@v1
        with:
          database: pgvector_raku_test
          dev-files: true
      - run: |
          cd /tmp
          git clone --branch v0.8.0 https://github.com/pgvector/pgvector.git
          cd pgvector
          make
          sudo make install
      - run: zef install DBIish DB::Pg
      - run: raku dbiish.raku
      - run: raku dbpg.raku
